name: CI/CD - Projeto Portais RFID

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests (if available)
      run: npm test --if-present
    
    - name: Build project
      run: npm run build --if-present
    
    - name: Check for vulnerabilities
      run: npm audit --audit-level moderate --if-present

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to production
      run: |
        echo "🚀 Deploying to production..."
        echo "✅ All tests passed!"
        echo "📦 Project built successfully!"
        echo "🔒 Security audit completed!"
        echo "🎯 Ready for deployment!"
